name: 'Publish common libraries'
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: test
              MYSQL_USER: test
              MYSQL_PASSWORD: test
          ports:
              - 3306

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: bbcoders/library-commons
          ref: development
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      
      - name: Install dependencies
        run: dotnet restore

      - name: Install dotnet-ef
        run: |
          dotnet tool install --global dotnet-ef

      - name: Sonarqube Begin
        run: | 
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"bbcoders_library-commons-workflow" /o:"bbcoders" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
      
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Apply Migrations
        run: dotnet ef database update

      - name: Test
        run: dotnet test --no-restore

      - name: Sonarqube end
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      